"""Add DriverProfile and Vehicle models

Revision ID: 08490f770c09
Revises: 94e937b4f532
Create Date: 2025-06-07 21:50:28.029793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08490f770c09'
down_revision = '94e937b4f532'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('license_number', sa.String(length=50), nullable=False),
    sa.Column('license_expiry_date', sa.Date(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('availability_status', sa.String(length=20), nullable=False),
    sa.Column('current_latitude', sa.Float(), nullable=True),
    sa.Column('current_longitude', sa.Float(), nullable=True),
    sa.Column('last_location_update', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_number')
    )
    with op.batch_alter_table('driver_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_driver_profiles_availability_status'), ['availability_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_driver_profiles_user_id'), ['user_id'], unique=True)

    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=30), nullable=True),
    sa.Column('license_plate', sa.String(length=20), nullable=False),
    sa.Column('vehicle_type', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicles_driver_id'), ['driver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicles_license_plate'), ['license_plate'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicles_license_plate'))
        batch_op.drop_index(batch_op.f('ix_vehicles_driver_id'))

    op.drop_table('vehicles')
    with op.batch_alter_table('driver_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_driver_profiles_user_id'))
        batch_op.drop_index(batch_op.f('ix_driver_profiles_availability_status'))

    op.drop_table('driver_profiles')
    # ### end Alembic commands ###
