"""Add Location and Ride models

Revision ID: 94e937b4f532
Revises: 74cac85cc9b5
Create Date: 2025-06-07 21:48:05.147760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94e937b4f532'
down_revision = '74cac85cc9b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('passenger_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('pickup_location_id', sa.Integer(), nullable=False),
    sa.Column('dropoff_location_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('estimated_fare', sa.Float(), nullable=True),
    sa.Column('actual_fare', sa.Float(), nullable=True),
    sa.Column('payment_status', sa.String(length=50), nullable=True),
    sa.Column('payment_intent_id', sa.String(length=255), nullable=True),
    sa.Column('vehicle_type_requested', sa.String(length=50), nullable=True),
    sa.Column('notes_for_driver', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dropoff_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['passenger_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pickup_location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rides', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rides_driver_id'), ['driver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rides_passenger_id'), ['passenger_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rides_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rides', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rides_status'))
        batch_op.drop_index(batch_op.f('ix_rides_passenger_id'))
        batch_op.drop_index(batch_op.f('ix_rides_driver_id'))

    op.drop_table('rides')
    op.drop_table('locations')
    # ### end Alembic commands ###
