"""Add is_admin to User model

Revision ID: 98a71da6d12e
Revises: 08490f770c09
Create Date: 2025-06-07 21:53:55.799759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98a71da6d12e'
down_revision = '08490f770c09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False))
        batch_op.create_index(batch_op.f('ix_users_is_admin'), ['is_admin'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_is_driver'), ['is_driver'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_is_driver'))
        batch_op.drop_index(batch_op.f('ix_users_is_admin'))
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
